DjangoUeditor/urls.py
# -*- coding: utf-8 -*-
import django
from .views import get_ueditor_controller

DJANGO_VERSION = django.VERSION[:2]


if DJANGO_VERSION >= (1, 8):
    from django.conf.urls import url
    urlpatterns = [
        url(r'^controller/$', get_ueditor_controller)
    ]

else:
    try:
        from django.conf.urls import patterns, url
    except ImportError:
        from django.conf.urls.defaults import patterns, url

    urlpatterns = patterns('',
        url(r'^controller/$', get_ueditor_controller)
    )

blog/urls.py
from django.conf.urls import url,include
from django.contrib import admin
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'',include('blog_app.urls')),
    url(r'',include('comments.urls'))

]

blog_app/urls.py
#!/usr/bin/env python
# -*- coding:utf-8 -*- 
# Author:fsh
from django.conf.urls import url,include
from . import views
from django.conf import settings
from DjangoUeditor import urls as DjangoUeditor_urls
from blog_app.feeds import AllPostsRssFeed
app_name='blog_app'#声明这个url是属于blog_app的
urlpatterns=[
    # url(r'^$',views.index,name='index'),
    url(r'^ueditor/', include(DjangoUeditor_urls)),
    url(r'^$',views.IndexView.as_view(),name='index'),
    # url(r'^$',views.index,name='index'),
    url(r'^post/(?P<pk>[0-9]+)$',views.PostDatailView.as_view(),name='detail'),
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{0,2})/$',views.ArtucleView.as_view(),name='archives'),
    url(r'^category/(?P<pk>[0-9]+)/$',views.CategoryView.as_view(),name='category'),
    url(r'^tag/(?P<tag>\w+)/$',views.TagsView.as_view(),name='tag'),
    url(r'^all/rss/$',AllPostsRssFeed(),name='rss')
]
if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

comments/urls.py
#!/usr/bin/env python
# -*- coding:utf-8 -*- 
# Author:fsh
from django.conf.urls import url
from . import views
app_name='comments'
urlpatterns=[
    url(r'^comment/post/(?P<post_pk>[0-9]+)/$',views.post_comment,name='post_comment'),
    url(r'^contact/',views.Contact,name='contact')
]

blog_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.six import python_2_unicode_compatible
from django.urls import reverse
from DjangoUeditor.models import UEditorField
# Create your models here.
@python_2_unicode_compatible#python2.xx
class Category(models.Model):#
    name=models.CharField(max_length=100)
    def __str__(self):
        return self.name
    class Meta:
        verbose_name='分类'
        verbose_name_plural='分类'
@python_2_unicode_compatible
class Tag(models.Model):
    name=models.CharField(max_length=100)
    class Meta:
        verbose_name='标签'
        verbose_name_plural='标签'
    def __str__(self):
        return self.name
@python_2_unicode_compatible
class Post(models.Model):
    title=models.CharField(max_length=100)
    body=UEditorField('内容', height=600, width=1000,
        default=u'', blank=True, imagePath="uploads/images/",
        toolbars='besttome', filePath='uploads/files/')
    create_time=models.DateTimeField(auto_now_add=True,editable=True)#创建时间
    modified_time=models.DateTimeField(auto_now=True,null=True)#修改时间
    excerpt=models.CharField(max_length=200,blank=True)#文章摘要
    category=models.ForeignKey(Category)#文章分类
    tags=models.ManyToManyField(Tag,blank=True)#标签
    author=models.ForeignKey(User)#继承django
    views=models.PositiveIntegerField(default=0)
    def increase_views(self):
        self.views+=1
        self.save(update_fields=['views'])
    def __str__(self):
        return self.title
    def get_absolute_url(self):
        return reverse('blog_app:detail',kwargs={'pk':self.pk})#这里的blog_app:detail就是app_name=blog_app声明好的，不申明会报错，detail就是name
    class Meta:
        ordering=['-create_time']#指定文章排序方式
        verbose_name='文章'
        verbose_name_plural='文章'

comments/forms.py
#!/usr/bin/env python
# -*- coding:utf-8 -*- 
# Author:fsh
from django import forms
from .models import Comment
# class CommentForm(forms.ModelForm):
#
#     class Meta:
#         model=Comment
#         fields=['name','email','url','text']


class CommentForm(forms.Form):
    name=forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','placeholder':"请输入您的名字",'max_length':25}))
    email=forms.EmailField(widget=forms.EmailInput(attrs={'class':'form-control','placeholder':'请输入您的邮箱'}))
    url=forms.URLField(widget=forms.URLInput(attrs={'class':'form-control','placeholder':'网址'}))
    text=forms.CharField(widget=forms.Textarea(attrs={'class':'form-control','placeholder':'评论内容'}))

blog_app/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse
from .models import Post,Category,Tag
from comments.forms import CommentForm
import markdown
from django.views.generic import ListView,DetailView
class IndexView(ListView):
    model = Post
    template_name = 'blog_app/index.html'
    context_object_name = 'post_list'
    paginate_by = 3
# def index(request):
#     post_list=Post.objects.all().order_by('-create_time')#-create_time是新文章排在前面
#     return render(request,'blog_app/index.html',context={'post_list':post_list})

class ArtucleView(IndexView):
    def get_queryset(self):
        return super(ArtucleView, self).get_queryset().filter(create_time__year=self.kwargs.get('year'),
                                    create_time__month=self.args.get('month'))
# def archives(request, year, month):
#     post_list = Post.objects.filter(create_time__year=year,
# #                                     create_time__month=month
#                                     )
#     return render(request, 'blog_app/index.html', context={'post_list': post_list})
# def detail(request,pk):#详情页面链接
#     post=get_object_or_404(Post,pk=pk)#不存在就直接报404
#     post.increase_views()
#     post.body = markdown.markdown(post.body,
#                                   extensions=[
#                                       'markdown.extensions.extra',
#                                       'markdown.extensions.codehilite',#代码高亮
#                                       'markdown.extensions.toc',
#                                   ])
#     form=CommentForm()
#     comment_list=post.comment_set.all()
#     context={
#         'post':post,
#         'form':form,
#         'comment_list':comment_list
#     }
#     return render(request,'blog_app/detail.html',context=context)
class PostDatailView(DetailView):
    model = Post
    template_name = 'blog_app/detail.html'
    context_object_name = 'post'

    def get(self,request,*args,**kwargs):
        response=super(PostDatailView, self).get(request,*args,**kwargs)
        self.object.increase_views()
        return response

    def get_object(self, queryset=None):
        post=super(PostDatailView, self).get_object(queryset=None)
        md = markdown.Markdown(extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
            'markdown.extensions.toc',
        ])
        post.body = md.convert(post.body)
        post.toc = md.toc
        print(post.toc)
        return post
    def get_context_data(self, **kwargs):
        context=super(PostDatailView, self).get_context_data(**kwargs)
        form=CommentForm()
        comment_list=self.object.comment_set.all()
        context.update(
            {
                'form':form,
                'comment_list':comment_list
            }
        )
        return context

class CategoryView(IndexView):
    def get_queryset(self):
        cate=get_object_or_404(Category,pk=self.kwargs.get('pk'))
        return super(CategoryView, self).get_queryset().filter(category=cate)
# def category(request,pk):#分类页面链接
#     cate=get_object_or_404(Category,pk=pk)
#     post_list=Post.objects.filter(category=cate)
#     return render(request,'blog_app/index.html',context={'post_list':post_list})

class TagsView(IndexView):
    def get_queryset(self):
        cate=get_object_or_404(Tag,name=self.kwargs.get('tag'))
        return super(TagsView, self).get_queryset().filter(tags=cate)


# def tags(request,tag):#标签页面链接
#     tag=get_object_or_404(Tag,name=tag)
#     post_list=Post.objects.filter(tags=tag)
#     return render(request,'blog_app/index.html',context={'pose_list':post_list})

templates/blog_app/about.html
<!DOCTYPE html>
<html>
	<head>
		<title>Black &amp; White</title>

		<!-- meta -->
		<meta charset="UTF-8">
	    <meta name="viewport" content="width=device-width, initial-scale=1">

	    <!-- css -->
		<link rel="stylesheet" href="../../blog_app/static/css/bootstrap.min.css">
		<link rel="stylesheet" href="css/ionicons.min.css">
		<link rel="stylesheet" href="../../blog_app/static/css/pace.css">
	    <link rel="stylesheet" href="../../blog_app/static/css/custom.css">

	    <!-- js -->
	    <script src="../../blog_app/static/js/jquery-2.1.3.min.js"></script>
	    <script src="../../blog_app/static/js/bootstrap.min.js"></script>
	    <script src="../../blog_app/static/js/pace.min.js"></script>
	    <script src="../../blog_app/static/js/modernizr.custom.js"></script>
	</head>

	<body id="page">
		<div class="container">	
			<header id="site-header">
				<div class="row">
					<div class="col-md-4 col-sm-5 col-xs-8">
						<div class="logo">
							<h1><a href="index.html"><b>Black</b> &amp; White</a></h1>
						</div>
					</div><!-- col-md-4 -->
					<div class="col-md-8 col-sm-7 col-xs-4">
						<nav class="main-nav" role="navigation">
							<div class="navbar-header">
  								<button type="button" id="trigger-overlay" class="navbar-toggle">
    								<span class="ion-navicon"></span>
  								</button>
							</div>

							<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
  								<ul class="nav navbar-nav navbar-right">
    								<li class="cl-effect-11"><a href="index.html" data-hover="Home">Home</a></li>
    								<li class="cl-effect-11"><a href="full-width.html" data-hover="Blog">Blog</a></li>
    								<li class="cl-effect-11"><a href="about.html" data-hover="About">About</a></li>
    								<li class="cl-effect-11"><a href="contact.html" data-hover="Contact">Contact</a></li>
  								</ul>
							</div><!-- /.navbar-collapse -->
						</nav>
						<div id="header-search-box">
							<a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
							<div id="search-form" class="search-form">
								<form role="search" method="get" id="searchform" action="#">
									<input type="search" placeholder="Search" required>
									<button type="submit"><span class="ion-ios-search-strong"></span></button>
								</form>				
							</div>
						</div>
					</div><!-- col-md-8 -->
				</div>
			</header>
		</div>

		<div class="content-body">
			<div class="container">
				<div class="row">
					<main class="col-md-12">
						<h1 class="page-title">About Me</h1>
						<article class="post">
							<div class="entry-content clearfix">
								<figure class="img-responsive-center">
									<img class="img-responsive" src="../../blog_app/static/img/me.jpg" alt="Developer Image">
								</figure>
								<p>Responsive web design offers us a way forward, finally allowing us to design for the ebb and flow of things. There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don’t look even slightly.</p>
								<p>Responsive web design offers us a way forward, finally allowing us to design for the ebb and flow of things. There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don’t look even slightly.</p>
								<div class="height-40px"></div>
								<h2 class="title text-center">Social</h2>
								<ul class="social">
									<li class="facebook"><a href="#"><span class="ion-social-facebook"></span></a></li>
									<li class="twitter"><a href="#"><span class="ion-social-twitter"></span></a></li>
									<li class="google-plus"><a href="#"><span class="ion-social-googleplus"></span></a></li>
									<li class="tumblr"><a href="#"><span class="ion-social-tumblr"></span></a></li>
								</ul>
							</div>
						</article>
					</main>
				</div>
			</div>
		</div>
		<footer id="site-footer">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<p class="copyright">&copy; 2014 ThemeWagon.com</p>
					</div>
				</div>
			</div>
		</footer>

		<!-- Mobile Menu -->
		<div class="overlay overlay-hugeinc">
			<button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
			<nav>
				<ul>
					<li><a href="index.html">Home</a></li>
					<li><a href="full-width.html">Blog</a></li>
					<li><a href="about.html">About</a></li>
					<li><a href="contact.html">Contact</a></li>
				</ul>
			</nav>
		</div>

		<script src="../../blog_app/static/js/script.js"></script>
		
	</body>
</html>

templates/blog_app/base.html
{% load staticfiles %}
{% load blog_tags %}
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}{% endblock %}</title>

    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
{#    高亮#}
    <link rel="stylesheet" href="{% static 'css/highlights/github.css' %}"/>
{#    <link rel="stylesheet" href="../../blog_app/static/css/bootstrap.min.css">#}
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
{#    <link rel="stylesheet" href="../../blog_app/static/css/pace.css">#}
{#    <link rel="stylesheet" href="../../blog_app/static/css/custom.css">#}
{#    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"/>#}
    <link rel="stylesheet" href="{% static 'css/pace.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/custom.css' %}"/>
    <!-- js -->
{#    <script src="{% static 'js/jquery-2.1.3.min.js' %}"></script>#}
{#    <script src="{% static 'js/bootstrap.min.js' %}"></script>#}
    <script src="{% static 'js/pace.min.js' %}"></script>
    <script src="{% static 'js/modernizr.custom.js' %}"></script>
{#    cdn加速#}
    <link href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.bootcss.com/jquery/2.1.3/jquery.min.js"></script>
    <script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>

<body>
<div class="container navbar-fixed-top">
    <header id="site-header">
        <div class="row">
            <div class="col-md-4 col-sm-5 col-xs-8">
                <div class="logo">
                    <a href="{% url 'blog_app:index' %}"><img src="{% static 'img/logo.png' %}" alt=""/></a>
                </div>

            </div><!-- col-md-4 -->
            <div class="col-md-8 col-sm-7 col-xs-4">
                <nav class="main-nav" role="navigation">
                    <div class="navbar-header">
                        <button type="button" id="trigger-overlay" class="navbar-toggle">
                            <span class="ion-navicon"></span>
                        </button>
                    </div>
                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="cl-effect-11"><a href="{% url 'blog_app:index' %}" data-hover="首页">首页</a></li>
                            <li class="cl-effect-11"><a href="#" data-hover="博客">博客</a></li>
                            <li class="cl-effect-11"><a href="about.html" data-hover="关于">关于</a></li>
                            <li class="cl-effect-11"><a href="{% url 'comments:contact'%}" data-hover="联系">联系</a></li>
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </nav>
                <div id="header-search-box">
                    <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
                    <div id="search-form" class="search-form">
                        <form role="search" method="get" id="searchform" action="#">
                            <input type="search" placeholder="搜索" required>
                            <button type="submit"><span class="ion-ios-search-strong"></span></button>
                        </form>
                    </div>
                </div>
            </div><!-- col-md-8 -->
        </div>
    </header>
</div>
{#<div class="copyrights">Collect from <a href="http://www.cssmoban.com/">网页模板</a></div>#}
{#<div class="copyrights">Modified by <a href="http://zmrenwu.com/">ド゛゜范的博客</a></div>#}

<div class="content-body">
    <div class="container">
        <div class="row">
            <main class="col-md-8">
                {% block main %}{% endblock %}
               <!-- 简单分页效果
                <div class="pagination-simple">
                    <a href="#">上一页</a>
                    <span class="current">第 6 页 / 共 11 页</span>
                    <a href="#">下一页</a>
                </div>
                -->
    <div class="pagination">
        <ul>
            {% for post in post_list %}
            <li>
                  <a href="{% url 'blog_app:category' post.pk %}">{{ post.name }}</a>
            </li>
        {% endfor %}
        </ul>
    </div>
            </main>
            <aside class="col-md-4 toc">
    <!-- <div class="widget widget-content">
        <h3 class="widget-title">文章目录</h3>
        {{ post.toc|safe }}
    </div> -->
                <div class="widget widget-recent-posts">
                    <h3 class="widget-title">最新文章</h3>
                    {% get_recent_posts as recent_post_list %}
                    <ul>
                        {% for post in recent_post_list %}
                        <li>
                            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                        </li>
{#                        <li>#}
{#                            <a href="#">Django 博客使用 Markdown 自动生成文章目录</a>#}
{#                        </li>#}
{#                        <li>#}
{#                            <a href="#">部署 Django 博客</a>#}
{#                        </li>#}
                            {% empty %}
                            <li>暂时没有文章</li>
                        {% endfor %}
                    </ul>
                </div>

                <div class="widget widget-archives">
                    <h3 class="widget-title">归档</h3>
                    {% archives as date_list %}
                    <ul>
                        {% for date in date_list %}
                            <li>
                                <a href="{%  url 'blog_app:archives' date.year date.month%}">{{ date.year }}年{{ date.month }}月</a>
                            </li>
                            {% empty %}
                            <li>暂无归档</li>
                        {% endfor %}
                    </ul>
                </div>

                <div class="widget widget-category">
                    <h3 class="widget-title">分类</h3>
                    {% get_categories as category_list %}
                    <ul>
                        {% for category in category_list %}
                        <li>
                            <a href="{% url 'blog_app:category' category.pk %}">{{ category.name }}<span class="post-count">({{ category.num_posts }})</span></a>
                        </li>
                            {% empty %}
                            <li>暂无分类</li>
                        {% endfor %}
                    </ul>
                </div>

                <div class="widget widget-tag-cloud">
                    <h3 class="widget-title">标签云</h3>
                    {% get_tags as tags %}
                    <ul>
                        {% for tag in tags %}
                        <li>
                            <a href="{% url 'blog_app:tag' tag.name %}">{{ tag.name }}</a>
                        </li>
                            {% empty %}
                            <li>
                                暂时没有标签
                            </li>
                        {% endfor %}
                    </ul>
                </div>

                <div class="rss">
                    <a href="{% url 'blog_app:rss' %}"><span class="ion-social-rss-outline"></span> RSS 订阅</a>
                </div>
            </aside>
        </div>
    </div>
</div>
<footer id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="copyright">&copy 2017 - <a href="#">ド゛゜范</a>的博客
                </p>
            </div>
        </div>
    </div>
</footer>

<!-- Mobile Menu -->
<div class="overlay overlay-hugeinc">
    <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
    <nav>
        <ul>
            <li><a href="{% url 'blog_app:index' %}">首页</a></li>
            <li><a href="full-width.html">博客</a></li>
            <li><a href="about.html">关于</a></li>
            <li><a href="contact.html">联系</a></li>
        </ul>
    </nav>
</div>

<script src="{% static 'js/script.js' %}"></script>

</body>
</html>

templates/blog_app/contact.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
    <title>{% block title %}{% endblock %}</title>

    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
{#    高亮#}
    <link rel="stylesheet" href="{% static 'css/highlights/github.css' %}"/>
{#    <link rel="stylesheet" href="../../blog_app/static/css/bootstrap.min.css">#}
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
{#    <link rel="stylesheet" href="../../blog_app/static/css/pace.css">#}
{#    <link rel="stylesheet" href="../../blog_app/static/css/custom.css">#}
{#    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"/>#}
    <link rel="stylesheet" href="{% static 'css/pace.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/custom.css' %}"/>
    <!-- js -->
{#    <script src="{% static 'js/jquery-2.1.3.min.js' %}"></script>#}
{#    <script src="{% static 'js/bootstrap.min.js' %}"></script>#}
    <script src="{% static 'js/pace.min.js' %}"></script>
    <script src="{% static 'js/modernizr.custom.js' %}"></script>
{#    cdn加速#}
    <link href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.bootcss.com/jquery/2.1.3/jquery.min.js"></script>
    <script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
    <div class="content-body">
			<div class="container">
				<div class="row">
					<main class="col-md-12">
						<article class="post">
							<div class="entry-content clearfix">
                                <h1 class="page-title">留言</h1>
								<form action="#" method="post" class="contact-form">
									<div class="row">
										<div class="col-md-6 col-md-offset-3">
											<input type="text" name="name" class="form-control" placeholder="名字" required>
											<input type="email" name="email" class="form-control" placeholder="Email" required>
											<input type="text" name="subject" class="form-control" placeholder="主题" required>
											<textarea name="message" rows="7" class="form-control" placeholder="留言内容" required></textarea>
											<button class="btn-send btn-5 btn-5b ion-ios-paperplane"><span>给我留言</span></button>
										</div>
									</div>	<!-- row -->
								</form>
							</div>
						</article>
					</main>
				</div>
			</div>
		</div>
<div class="overlay overlay-hugeinc">
    <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
    <nav>
        <ul>
            <li><a href="{% url 'blog_app:index' %}">首页</a></li>
            <li><a href="full-width.html">博客</a></li>
            <li><a href="about.html">关于</a></li>
            <li><a href="contact.html">联系</a></li>
        </ul>
    </nav>
</div>

<script src="{% static 'js/script.js' %}"></script>

</body>
</html>

templates/blog_app/detail.html
{% extends 'blog_app/base.html' %}
{% block title %}{% load staticfiles %}
{{ post.title }}
{% endblock %}
{% block main %}
<article class="post post-{{ post.pk }}">
  <header class="entry-header">
    <h1 class="entry-title">{{ post.title }}</h1>
    <div class="entry-meta">
      <span class="post-category"><a href="#">{{ post.category.name }}</a></span>
      <span class="post-date"><a href="#"><time class="entry-date"
                                                datetime="{{ post.create_time }}">{{ post.create_time }}</time></a></span>
      <span class="post-author"><a href="#">{{ post.author }}</a></span>
      <span class="comments-link"><a href="#">{{ post.comment_set.count }}评论</a></span>
      <span class="views-count"><a href="{{ post.get_absolute_url }}">{{ post.views }}阅读</a></span>
    </div>
  </header>
  <div class="entry-content clearfix">
    {{ post.body|safe }}
  </div>
</article>
<section class="comment-area" id="comment-area"><hr>
    <h3>发表评论</h3>
    <form action="{% url 'comments:post_comment' post.pk %}" method="post" class="comment-form">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-4">
{#                <label for="id_name">你的名字：</label>#}
                {{ form.name }}
                {{ from.name.errors }}
{#                <input type="text" id="id_name" name="name"  class="form-control" placeholder="请输入您的名字" required>#}
            </div>
            <div class="col-md-4">
{#                <label for="id_email">你的邮箱：</label>#}
                {{ form.email }}
                {{ form.email.errors }}

{#                <input type="email" id="id_email" name="email" class="form-control" placeholder="请输入您的邮箱" required>#}
            </div>
            <div class="col-md-4">
{#                 <label for="id_url">网址：</label>#}
                    {{ form.url }}
                    {{ form.url.errors }}
{#                <label for="id_url">网址：</label>#}
{#                <input type="text" id="id_url" name="url">#}
            </div>
            <div class="col-md-12">
                {{ form.text }}
                {{ form.text.errors }}
{#                <textarea name="comment" id="id_comment"  class="form-control" placeholder="请输入您的评论内容" required></textarea>#}
                <button type="submit" class="btn btn-primary btn-lg">发表</button>
            </div>
        </div>    <!-- row -->
    </form>
    <div class="comment-list-panel">
        <h3>评论列表，共 <span>{{ post.comment_set.count }}</span> 条评论</h3>
        <ul class="comment-list list-unstyled">
            {% for comment in comment_list %}
            <li class="comment-item">
                <span class="img"><img src="{% static 'img/me.jpg' %}" alt=""></span>
                <span class="nickname">{{ comment.name }}</span>
                <time class="submit-date time" datetime="{{ comment.created_time }}">{{ comment.created_time }}</time>
                <div class="text">
                    {{ comment.text }}
                </div>
            {% empty %}
            暂无评论
            </li>

            {% endfor %}
        </ul>
    </div>
</section>
{% endblock main %}
{##右边的板块#}
{% block toc %}
    <div class="widget widget-content">
        <h3 class="widget-title">文章目录</h3>
        <ul>
            <li>
                <a href="#">教程特点</a>
            </li>
            <li>
                <a href="#">谁适合这个教程</a>
            </li>
            <li>
                <a href="#">在线预览</a>
            </li>
            <li>
                <a href="#">资源列表</a>
            </li>
            <li>
                <a href="#">获取帮助</a>
            </li>
        </ul>
    </div>
{% endblock toc %}

templates/blog_app/index.html
{% extends 'blog_app/base.html' %}
{% block title %}欢迎来到ド゛゜范的博客{% endblock %}
{% block main %}
<main>
{% for post in post_list %}
     <article class="toc post post-{{ post.pk }}">
         <header class="entry-header">
             <h1 class="entry-title">
                 <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
             </h1>
             <div class="entry-meta">
                 <span class="post-category"><a href="#">{{ post.category }}</a></span>
                 <span class="post-date"><a href="#"><time class="entry-date"
                                                                      datetime="{{ post.create_time }}">{{ post.create_time }}</time></a></span>
                 <span class="post-author"><a href="#">{{ post.author }}</a></span>
                 <span class="comments-link"><a href="#">{{ post.comment_set.count }}评论</a></span>
                 <span class="views-count"><a href="{{ post.get_absolute_url }}">{{ post.views }}阅读</a></span>
             </div>
         </header>
         <div class="entry-content clearfix">
             <p>{{ post.body|truncatechars_html:54|striptags|safe }}</p>
             <div class="read-more cl-effect-14">
                 <a href="{{ post.get_absolute_url }}" class="more-link">阅读全文 <span class="meta-nav">→</span></a>
             </div>
         </div>
     {% empty %}
     <div class="no-post">没有其他文章了</div>
     </article>
    {% endfor %}
{% if is_paginated %}
<div class="pagination-simple">
  <!-- 如果当前页还有上一页，显示一个上一页的按钮 -->
  {% if page_obj.has_previous %}
    <a href="?page={{ page_obj.previous_page_number }}">上一页</a>
  {% endif %}
  <!-- 显示当前页面信息 -->
  <span class="current">第 {{ page_obj.number }} 页 / 共 {{ paginator.num_pages }} 页</span>
  <!-- 如果当前页还有下一页，显示一个下一页的按钮 -->
  {% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}">下一页</a>
  {% endif %}
</div>
{% endif %}
</main>
{% endblock main %}